### ISSUE TITLE
setdropsAsLoot NoSuchMethodError

### ISSUE THREAD

**Issue by frakier** [AzureZhen/Mine-and-Slash-AutoCompat-114#2]
curios-FORGE-1.14.4-1.0.6.jar
Mine+and+Slash-1.14.4-2.9.3.jar
MS+Auto-Compat-1.14.4-1.5.1.jar

Tried with multiple versions of forge from 28.1.76 to 28.1.114
I even deleted the config folder contents to be safe

the error...
Caught exception during event InterModProcessEvent dispatch for modid azurecompat
java.lang.NoSuchMethodError: com.robertx22.mine_and_slash.config.compatible_items.ConfigItem.setdropsAsLoot(Z)Lcom/robertx22/mine_and_slash/config/compatible_items/ConfigItem;

log attached [scrubbed the person info]
[latest.log](https://github.com/AzureDoom/Mine-and-Slash-AutoCompat/files/4049826/latest.log)

**Comment by AzureDoom** [comment]
You need to update your Mine and Slash to 2.9.4

**Comment by frakier** [comment]
thanks, though I had got all the mods that needed updating as they came out guess I missed one or just messed up somewhere.

**Comment by AzureDoom** [comment]
Np. I'll update the minimum requirement here tonight
