### ISSUE TITLE
erro process_imc

### ISSUE THREAD

**Issue by Ashtar084** [AzureZhen/Mine-and-Slash-AutoCompat-114#3]
**[after updating Mine+and+Slash-1.15.2-3.1.0 i have this erro**

error event stage process_imc

What can it be?

Thank you very much in advance

**Comment by AzureDoom** [comment]
Mine and Slash 3.1.x for 1.15.2 has been released. This updates breaks all my autocompability so if you use my mods, do not update yet

**Comment by Ashtar084** [comment]
yes, exactly what i'm doing.
  thanks for responding quickly. (☞ﾟヮﾟ)☞
    do you expect to fix it later?
       if so, could you please add compatibility with <>travellers boots<>

    and sorry my english.   =D

**Comment by Ashtar084** [comment]
thank you so much for adding compatibility with travellers boots
great mod thanks !!!
