### ISSUE TITLE
Guards dont autocompat with Weapons

### ISSUE THREAD

**Issue by 2001plee** [AzureZhen/Mine-and-Slash-AutoCompat-114#4]
Hi, I've been using a modpack with Mine and slash and Minecolonies and some other mods. Its been going great, but guards dont seem to use the levels and damage of the mine and slash meaning they do basically 0 damage to high level mobs.

**Comment by AzureDoom** [comment]
Make sure your colony is leveled enough. I also think Mine colonies doesn't like the NBT data being long.
