### ISSUE TITLE
[1.15.2]Request compatibility Mod

### ISSUE THREAD

**Issue by EnterFor** [AzureZhen/Mine-and-Slash-AutoCompat-114#5]
https://www.curseforge.com/minecraft/mc-mods/explorercraft-worldexpansion

This Mod adds some gear and mobs
I hope to add compatibility
thanks in advance

**Comment by AzureDoom** [comment]
You no longer need this in 1.15.2 simply go to the world save in singleplayer or the server and in serverconfig turn on auto compatibility!
